esphome:
  name: ac-office

esp8266:
  board: nodemcuv2
  # esp12e

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0
#  hardware_uart: UART1

debug:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret wifi_ip

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password

external_components:
  - source:
      type: git
      url: https://github.com/GrKoR/esphome_aux_ac_component
      ref: master
#    refresh: 0s
#  - source: github://GrKoR/esphome_aux_ac_component@master
#    components: [ aux_ac ]
#    refresh: 0s
#  - source: esphome_aux_ac_component/components

uart:
  id: ac_uart_bus
#  tx_pin: GPIO15
#  rx_pin: GPIO13
#  tx_pin: GPIO3
#  rx_pin: GPIO1
#  tx_pin: RX
#  rx_pin: TX
  tx_pin: D2
  rx_pin: D1
#  tx_pin: GPIO4
#  rx_pin: GPIO5
  baud_rate: 4800
  data_bits: 8
  parity: EVEN
  stop_bits: 1
#  debug:
#    direction: BOTH
#    dummy_receiver: false
#    after:
#      delimiter: "\n"
#    sequence:
#      - lambda: UARTDebug::log_string(direction, bytes);

climate:
  - platform: aux_ac
    name: "AC Office"
    id: ac_office
    uart_id: ac_uart_bus
    period: 7s
    show_action: true
    display_inverted: false
    indoor_temperature:
      name: AC Indoor Temperature
      id: ac_indoor_temp
      internal: false
    outdoor_temperature:
      name: AC Outdoor Temperature
      id: ac_outdoor_temp
      internal: false
    outbound_temperature:
      name: AC Colant Outbound Temperature
      id: ac_outbound_temp
      internal: false
    inbound_temperature:
      name: AC Colant Inbound Temperature
      id: ac_inbound_temp
      internal: false
    compressor_temperature:
      name: AC Compressor Temperature
      id: ac_strange_temp
      internal: false
    defrost_state:
      name: AC Defrost State
      id: ac_defrost_state
      internal: false
    invertor_power:
      name: AC Invertor Power
      id: ac_invertor_power
      internal: false
    preset_reporter:
      name: AC Preset Reporter
      id: ac_preset_reporter
      internal: false
    display_state:
      name: AC Display State
      id: ac_display_state
      internal: false
    visual:
      min_temperature: 16
      max_temperature: 32
      temperature_step: 1
    supported_modes:
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    custom_fan_modes:
      - MUTE
      - TURBO
    supported_presets:
      - SLEEP
    custom_presets:
      - CLEAN
      - HEALTH
      - ANTIFUNGUS
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH

switch:
  - platform: template
    name: AC Office Display
    lambda: |-
      if (id(ac_display_state).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - aux_ac.display_on: ac_office
    turn_off_action:
      - aux_ac.display_off: ac_office

button:
  - platform: template
    name: AC Office VLouver Stop
    icon: "mdi:circle-small"
    on_press:
      - aux_ac.vlouver_stop: ac_office
    
  - platform: template
    name: AC Office VLouver Swing
    icon: "mdi:pan-vertical"
    on_press:
      - aux_ac.vlouver_swing: ac_office
    
  - platform: template
    name: AC Office VLouver Top
    icon: "mdi:pan-up"
    on_press:
      - aux_ac.vlouver_top: ac_office
    
  - platform: template
    name: AC Office VLouver Middle Above
    icon: "mdi:pan-top-left"
    on_press:
      - aux_ac.vlouver_middle_above: ac_office
    
  - platform: template
    name: AC Office VLouver Middle
    icon: "mdi:pan-left"
    on_press:
      - aux_ac.vlouver_middle: ac_office
    
  - platform: template
    name: AC Office VLouver Middle Below
    icon: "mdi:pan-bottom-left"
    on_press:
      - aux_ac.vlouver_middle_below: ac_office
    
  - platform: template
    name: AC Office VLouver Bottom
    icon: "mdi:pan-down"
    on_press:
      - aux_ac.vlouver_bottom: ac_office


number:
  - platform: template
    name: AC Office Vertical Louver
    id: ac_office_vlouver
    icon: "mdi:circle-small"
    mode: "slider"
    min_value: 0
    max_value: 6
    step: 1
    set_action:
      then:
        - lambda: !lambda |-
            if (x == 6) x = 7;  // 6 is incorrect louver position, 7 is stopped louver
            id(ac_office).setVLouverSequence( static_cast<esphome::aux_ac::ac_louver_V>(x) );